runtime: python39
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: dist/alfian-portfolio/index.html
    upload: dist/alfian-portfolio/index.html
  - url: /
    static_dir: dist/alfian-portfolio

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
