version: '3.4'

services:
  alfianportfolio:
    image: alfianportfolio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7000:7000
